"""Initial migration

Revision ID: 16b8c7a846c6
Revises: 
Create Date: 2026-02-14 14:01:12.691824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b8c7a846c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_expedition_service',
    sa.Column('id_expedition_service', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_expedition_service')
    )
    op.create_index(op.f('ix_mst_expedition_service_id_expedition_service'), 'mst_expedition_service', ['id_expedition_service'], unique=False)
    op.create_table('mst_product',
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('product_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_index(op.f('ix_mst_product_id_product'), 'mst_product', ['id_product'], unique=False)
    op.create_table('mst_users',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_mst_users_email'), 'mst_users', ['email'], unique=True)
    op.create_index(op.f('ix_mst_users_id_user'), 'mst_users', ['id_user'], unique=False)
    op.create_table('mst_carts',
    sa.Column('id_cart', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=True),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['mst_product.id_product'], ),
    sa.ForeignKeyConstraint(['id_user'], ['mst_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_index(op.f('ix_mst_carts_id_cart'), 'mst_carts', ['id_cart'], unique=False)
    op.create_table('mst_transactions',
    sa.Column('id_transaction', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('id_expedition_service', sa.UUID(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_expedition_service'], ['mst_expedition_service.id_expedition_service'], ),
    sa.ForeignKeyConstraint(['id_user'], ['mst_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_index(op.f('ix_mst_transactions_id_transaction'), 'mst_transactions', ['id_transaction'], unique=False)
    op.create_table('trn_product_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['mst_product.id_product'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trn_product_stock_id'), 'trn_product_stock', ['id'], unique=False)
    op.create_table('trn_transaction_items',
    sa.Column('id_transaction_item', sa.UUID(), nullable=False),
    sa.Column('id_transaction', sa.UUID(), nullable=True),
    sa.Column('id_product', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['mst_product.id_product'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['mst_transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_transaction_item')
    )
    op.create_index(op.f('ix_trn_transaction_items_id_transaction_item'), 'trn_transaction_items', ['id_transaction_item'], unique=False)
    op.create_table('trn_transaction_status',
    sa.Column('id_transaction_status', sa.UUID(), nullable=False),
    sa.Column('id_transaction', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'FAILED', 'CANCELLED', 'PACKING', 'COMPLETED', 'SHIPPED', name='transactionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaction'], ['mst_transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_transaction_status')
    )
    op.create_index(op.f('ix_trn_transaction_status_id_transaction_status'), 'trn_transaction_status', ['id_transaction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trn_transaction_status_id_transaction_status'), table_name='trn_transaction_status')
    op.drop_table('trn_transaction_status')
    op.drop_index(op.f('ix_trn_transaction_items_id_transaction_item'), table_name='trn_transaction_items')
    op.drop_table('trn_transaction_items')
    op.drop_index(op.f('ix_trn_product_stock_id'), table_name='trn_product_stock')
    op.drop_table('trn_product_stock')
    op.drop_index(op.f('ix_mst_transactions_id_transaction'), table_name='mst_transactions')
    op.drop_table('mst_transactions')
    op.drop_index(op.f('ix_mst_carts_id_cart'), table_name='mst_carts')
    op.drop_table('mst_carts')
    op.drop_index(op.f('ix_mst_users_id_user'), table_name='mst_users')
    op.drop_index(op.f('ix_mst_users_email'), table_name='mst_users')
    op.drop_table('mst_users')
    op.drop_index(op.f('ix_mst_product_id_product'), table_name='mst_product')
    op.drop_table('mst_product')
    op.drop_index(op.f('ix_mst_expedition_service_id_expedition_service'), table_name='mst_expedition_service')
    op.drop_table('mst_expedition_service')
    # ### end Alembic commands ###