"""Add cascade delete to product stock

Revision ID: 6a6f50cd9968
Revises: 16b8c7a846c6
Create Date: 2026-02-14 15:45:59.947225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6f50cd9968'
down_revision: Union[str, None] = '16b8c7a846c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trn_product_stock_id_product_fkey'), 'trn_product_stock', type_='foreignkey')
    op.create_foreign_key(None, 'trn_product_stock', 'mst_product', ['id_product'], ['id_product'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trn_product_stock', type_='foreignkey')
    op.create_foreign_key(op.f('trn_product_stock_id_product_fkey'), 'trn_product_stock', 'mst_product', ['id_product'], ['id_product'])
    # ### end Alembic commands ###